/**
 * 全局颜色资源文件
 */
export default class ColorConstants {

  static readonly COLOR_ALPHA: string = '#00000000'
  static readonly COLOR_E4E5Ef: string = '#E4E5EF'

  static readonly COLOR_16A185: string = '#16A185'

  static readonly COLOR_4016a185: string = '#4016a185'

  static readonly COLOR_2D2F38: string = '#2D2F38'

  static readonly COLOR_E35A43: string = '#E35A43'

  static readonly COLOR_6F7281: string = '#6F7281'

  static readonly COLOR_F0FAF8: string = '#F0FAF8'

  static readonly COLOR_F4F5FA:string = '#F4F5FA'

}

@Styles function globalFancy() {
  .width(150)
  .height(100)
  .backgroundColor(Color.Pink)
}